### ISSUE TITLE
Application won't launch after running "hifiscan"

### ISSUE THREAD

**Issue by halkony** [erdewit/HiFiScan#1]
Hello,

Very interested in using this project.
I am running on Python 3.9.6. After `pip install hifiscan` running `hifiscan` in Windows leads to this.
![image](https://user-images.githubusercontent.com/15790371/189532986-c179295d-b222-4a28-8c61-f6a611b353a1.png)

I've rebooted and also tried reinstalling as admin with no luck. Where can I find logs to help resolve this issue?

Thanks,
Nate

**Comment by erdewit** [comment]
Can you try with the old Windows command shell (cmd)?

An alternative way to start the app is with
```
python -m hifiscan
```

**Comment by halkony** [comment]
Solved, was missing a dependency.

![image](https://user-images.githubusercontent.com/15790371/189713601-a2c0d537-2d48-45db-82ba-e2a01aa65006.png)
