### ISSUE TITLE
measure left and right separately

### ISSUE THREAD

**Issue by balbuze** [erdewit/HiFiScan#10]
Hello!
What a fast development !
Do you consider to add the possibility to measure left and right separately?
BR

**Comment by erdewit** [comment]
> Do you consider to add the possibility to measure left and right separately?

I'm not sure yet how that will look like.

It's possible right now by setting the system volume to only left/right, measure the impulse for each channel and then combine them in a sound editor into one stereo impulse. This is of course a bit awkward and it would be nice to simply this.

**Comment by balbuze** [comment]
hello!
on some system (mine ;-)), you can't mute a channel.
The idea is to simply play the sweep and measure on a chosen channel in HIFIscan, export the wav, and doing the same for the orher. No need to combine results in a single file.
In summary, a button to play left, right, both.

**Comment by erdewit** [comment]
> In summary, a button to play left, right, both.

Yes that's a good idea.
