### ISSUE TITLE
sweep length

### ISSUE THREAD

**Issue by balbuze** [erdewit/HiFiScan#11]
Can you increase sweep length setting up to 30 seconds for a better noise rejection?
BR

**Comment by erdewit** [comment]
Sure that's no problem. It does get to be sluggish though with that size and I think it's better to use the new **Store** button to store three 10s measurements . That should given the same S/N ratio.

**Comment by balbuze** [comment]
You are right. Really, I'm impressed by your work. I use to do it with Rew and convert impulse with Drc--fir.
Your solution is much more easy. Results must be compared though 🙂

**Comment by erdewit** [comment]
There's a sweep length of 30s now in v1.3.0.
