### ISSUE TITLE
Samplerate of impulse response

### ISSUE THREAD

**Issue by Naozumi520** [erdewit/HiFiScan#13]
Both of my input and output devices are 48000Hz and cannot be set. I exported the WAV file and load it to Equalizer APO but this showing me this. Is it possible to get a WAV with 48000Hz of samplerate? 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/52615455/201466473-d9ec9601-6fed-466b-a8a7-fc0728492202.png">

**Comment by erdewit** [comment]
I'm not sure where the 44100 rate comes from. If the system uses 48000 then the response should have that rate as well.

**Comment by shrx** [comment]
Same issue here.

some more details: 

Microphone: Elgato Wave 3

Sample rate: 48 kHz

Bit depth: 24

OS: Windows 10

It looks like `sounddevice` creates a `Stream` object with the sample rate set to 44100 by default.

**Comment by ValentinDragomir** [comment]
Same issue here. I've converted the sample from 44100 Hz to 48000 Hz with Audacity,

I presume that shouldn't result in any noticeable difference. However, a fix would be nice for maximum accuracy!

Is there any way we can help?

Edit: There already is a pull request to change the default sample rate from 44100 Hz to 48000 Hz which is still open...
        I've learned that you can manually edit the audio.py (C:\Users\"User"\AppData\Local\Programs\Python\Python311\Lib\site-packages\hifiscan - on Windows 11 in my case) to change the default sample rate as shown here:
        https://github.com/erdewit/HiFiScan/pull/16/commits/09e98a451bda3e5498f160e794d39768e5cdc4a5

**Comment by erdewit** [comment]
Version 1.5.0 has added a combobox for choosing the sample rate.
