### ISSUE TITLE
Cheapest microphone you would consider viable for calibration? 

### ISSUE THREAD

**Issue by lukaszliniewicz** [erdewit/HiFiScan#17]
Thank you very much for creating this software, the idea is amazing and I look forward to trying it out! What microphone would be the absolute cheapest option to yield me usable results? I have a Zoom h1n recorder that can work as a usb mic, is that an option?

**Comment by erdewit** [comment]
>  I have a Zoom h1n recorder that can work as a usb mic, is that an option?

That should work very well.
