### ISSUE TITLE
Possible to import microphone calibration file?

### ISSUE THREAD

**Issue by exislow** [erdewit/HiFiScan#3]
What a beautiful project -- thank you very much!

To be able to record frequencies accordingly a calibrated microphone is necessary. To accomplish this a microphone is usually measured and a calibration file is provided (which contains the microphone correction values) which can be used with different measurement applications, e.g. REW, to create accurate recordings. For instance, miniDSP provides such calibration files with their UMIKs out of the box, see https://www.minidsp.com/products/acoustic-measurement/umik-1 ("Unique Calibration File Download").

Is it possible to import such a calibration file into this application or do you plan to implement this? This would be awesome and will totally improve the measurement quality, hence also the calculation of correction values.

**Comment by erdewit** [comment]
Is there a standard format for these mic calibration files?

**Comment by wildekek** [comment]
Example file attached
[7018230.txt](https://github.com/erdewit/HiFiScan/files/9550571/7018230.txt)

**Comment by exislow** [comment]
Here are two more:

[7044645_90deg.txt](https://github.com/erdewit/HiFiScan/files/9551463/7044645_90deg.txt)
[7044645.txt](https://github.com/erdewit/HiFiScan/files/9551468/7044645.txt)

**Comment by erdewit** [comment]
Thank you both for the example files. That looks like a convenient format for adding manual corrections as well.

**Comment by naggie** [comment]
Yes I think room EQ wizard uses a similar format for manual corrections (for house curves) too. I've used a harman curve with a bass boost for my system. Not yet with HiFiScan, but I'm excited to try!


Here's the curve in dirac format, and another similar one in what REW accepts. Note that the REW one is almost identical to the microphone calibration files:

[Harman-Dirac-8dB.txt](https://github.com/erdewit/HiFiScan/files/9559362/Harman-8dB.txt)
[Harman Curve.txt](https://github.com/erdewit/HiFiScan/files/9559374/Harman.Curve.txt)

**Comment by exislow** [comment]
Here is my target / house curve I use in REW: [house_curve.txt](https://github.com/erdewit/HiFiScan/files/9560594/house_curve.txt)

Would it be possible, that an import of an house curve is also possible?

**Comment by erdewit** [comment]
> Would it be possible, that an import of an house curve is also possible?

Sure.

About that house curve:
```
31.5 6
40 5.9
50 5.5
63 4.9
80 3.7
100 2.5
125 1.3
160 0.6
200 0.2
250 0
1000 -1
32000 -6
```
what is supposed to happen in between the points, for example is it linearly interpolated or is some form of smooth interpolation generally used.

**Comment by naggie** [comment]
According to this https://www.roomeqwizard.com/help/help_en-GB/html/housecurve.html it's linear by default, logarithmic optionally. I suppose it will look smoothed on a logarithmic scale if it's linear, and the opposite if not.

(By the way, thanks for writing HifiScan @erdewit -- I think it could be really cool as an alternative to REW+minidsp+dirac if used with minidsp-rs one day)

**Comment by erdewit** [comment]
That's very good documentation from REW. The logarithmic interpolation would make the most sense, as it gives a straight line between points on a log-log spectrum plot. I've written the math for this and it works well in a notebook, what is left to do is the GUI part.

**Comment by naggie** [comment]
Great! Though they would look straight, what's best sonically? Would there be a difference to the room correction result?

**Comment by erdewit** [comment]
Here's the earlier house curve, with linear (orange) and log (blue) interpolation. 

![image](https://user-images.githubusercontent.com/3875748/190497903-ec5a264c-32ea-437c-847e-3b1456442ab3.png)

The orange curve is just weird and probably not intended.

**Comment by erdewit** [comment]
Setting the microphone calibration and target curve is now available in v1.1.0. An example is added here:
https://github.com/erdewit/HiFiScan#using-a-target-curve
Upgrading to the new version is done with ``pip install -U hifiscan``.

**Comment by exislow** [comment]
Amazing. Thank you very much! I will test it later.

**Comment by naggie** [comment]
Amazing indeed! Thanks @erdewit !

**Comment by wildekek** [comment]
Nice work!
