### ISSUE TITLE
'hifiscan' not activating the program

### ISSUE THREAD

**Issue by ghost** [erdewit/HiFiScan#7]
It appears that no matter where/with what rights you enter the command: 'hifiscan', the program just does not want to start from console.

**Comment by ghost** [comment]
Maybe handy to add: 
All dependencies are satisfied however there is some issue with Shiboken. 

    from shiboken6.Shiboken import *
ImportError: DLL load failed while importing Shiboken: The specified procedure could not be found.

Trying to pip install it manually is also no bueno. (Some errors with missing attributes)

**Comment by erdewit** [comment]
Shiboken is a part of PySide6. I'm not really happy with PySide6 and will switch to PyQt6, which will fix this issue as well.
